# services:
#   ntfy:
#     image: binwiederhier/ntfy
#     container_name: ntfy
#     command:
#       - serve
#     environment:
#       - TZ=Amercia/St_Lucia # optional: set desired timezone
#     user: 1000:1000 # optional: replace with your own user/group or uid/gid
#     volumes:
#       - /var/cache/ntfy:/var/cache/ntfy
#       - /etc/ntfy:/etc/ntfy
#     ports:
#       - 1336:80
#     healthcheck: # optional: remember to adapt the host:port to your environment
#       test:
#         [
#           "CMD-SHELL",
#           "wget -q --tries=1 http://localhost:1336/v1/health -O - | grep -Eo '\"healthy\"\\s*:\\s*true' || exit 1",
#         ]
#       interval: 60s
#       timeout: 10s
#       retries: 3
#       start_period: 40s
#     restart: unless-stopped

services:
  ntfy:
    image: binwiederhier/ntfy
    healthcheck: # optional: remember to adapt the host:port to your environment
      test:
        [
          "CMD-SHELL",
          "wget -q --tries=1 http://localhost:1336/v1/health -O - | grep -Eo '\"healthy\"\\s*:\\s*true' || exit 1",
        ]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    container_name: ntfy
    environment:
      NTFY_BASE_URL: https://ntfy.kingship.info
      NTFY_CACHE_FILE: /var/lib/ntfy/cache.db
      # NTFY_AUTH_FILE: /var/lib/ntfy/auth.db
      # NTFY_AUTH_DEFAULT_ACCESS: deny-all
      # NTFY_BEHIND_PROXY: true
      NTFY_ATTACHMENT_CACHE_DIR: /var/lib/ntfy/attachments
      # NTFY_ENABLE_LOGIN: true
      NTFY_UPSTREAM_BASE_URL: https://ntfy.sh
      # NTFY_WEB_PUSH_PUBLIC_KEY: <public_key>
      # NTFY_WEB_PUSH_PRIVATE_KEY: <private_key>
      NTFY_WEB_PUSH_FILE: /var/lib/ntfy/webpush.db
      NTFY_WEB_PUSH_EMAIL_ADDRESS: kingship.lc@gmail.com
    volumes:
      - ./:/var/lib/ntfy
      - /var/cache/ntfy:/var/cache/ntfy
      - /etc/ntfy:/etc/ntfy
    ports:
      - 1336:80
    command: serve

